apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: cm9vdA==  # Base64 encoded value of "root"
  DB_PASSWORD: UGFzc0AxMjM=  # Base64 encoded value of "Pass@123"
  PAYU_KEY: Sm15ZjRy
  PAYU_SALT: U3JLS3ZlS0JmMm9FM0p1SFd4Q3lYQkx6cmR6MXhZeA==
  RAZORPAY_KEY_ID: cnpwX2xpdmVfazhsMl4haTBpckNzNA==
  RAZORPAY_KEY_SECRET: QUsxbGFCSWtkcmZUSmFrc2JXVzdyTk5Q

